In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
import sklearn as sk
from sklearn import tree # for our decision tree

In [2]:
tita=pd.read_csv('titanic_dataset.csv')

In [3]:
tita.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  Sib_Sp  \
0                            Braund, Mr. Owen Harris    male  22.0       1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0       1   
2                             Heikkinen, Miss. Laina  female  26.0       0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0       1   
4                           Allen, Mr. William Henry    male  35.0       0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
tita.info

<bound method DataFrame.info of      PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  Sib_Sp  \
0                              Braund, Mr. Owen Harris    male  22.0       1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0       1   
2                               Heikkinen, Miss. Laina  female  26.0       0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0       1   
4                             Allen, Mr. William Henry    male  35.0       0   
..                             

In [5]:
tita.describe()

PassengerId    Survived      Pclass         Age      Sib_Sp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [6]:
bins = [0, 5, 17, 25, 50, 80]
labels = ['Infant', 'Kid', 'Young', 'Adult', 'Old']
tita['Age'] = pd.cut(tita['Age'], bins = bins, labels=labels)

In [7]:
pd.DataFrame(tita['Age'].value_counts())

Age
Adult   349
Young   188
Kid      69
Old      64
Infant   44

In [8]:
tita.drop(columns=['Name','Sib_Sp','Parch','Ticket','Cabin','Fare','Embarked'],inplace=True,axis=1)

In [9]:
tita.describe

<bound method NDFrame.describe of      PassengerId  Survived  Pclass     Sex    Age
0              1         0       3    male  Young
1              2         1       1  female  Adult
2              3         1       3  female  Adult
3              4         1       1  female  Adult
4              5         0       3    male  Adult
..           ...       ...     ...     ...    ...
886          887         0       2    male  Adult
887          888         1       1  female  Young
888          889         0       3  female    NaN
889          890         1       1    male  Adult
890          891         0       3    male  Adult

[891 rows x 5 columns]>

In [10]:
tita.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   PassengerId  891 non-null    int64   
 1   Survived     891 non-null    int64   
 2   Pclass       891 non-null    int64   
 3   Sex          891 non-null    object  
 4   Age          714 non-null    category
dtypes: category(1), int64(3), object(1)
memory usage: 29.0+ KB


In [11]:
tita['Pclass'].unique()

array([3, 1, 2], dtype=int64)

In [12]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder # to convert non numeric to numeric

In [13]:
lb=LabelEncoder()

In [14]:
tita['PassengerId']=lb.fit_transform(tita['PassengerId'])
tita['Survived']=lb.fit_transform(tita['Survived'])
tita['Pclass']=lb.fit_transform(tita['Pclass'])
tita['Sex']=lb.fit_transform(tita['Sex'])
tita['Age']=lb.fit_transform(tita['Age'])

In [15]:
tita.head()

PassengerId  Survived  Pclass  Sex  Age
0            0         0       2    1    4
1            1         1       0    0    0
2            2         1       2    0    0
3            3         1       0    0    0
4            4         0       2    1    0

In [16]:
y=tita['Survived']
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [17]:
X=tita.drop('Survived',inplace=True,axis=1)

In [18]:
X_train,X_test,y_train,y_test=train_test_split(tita,y,test_size=0.3,random_state=100)

In [19]:
clf=DecisionTreeClassifier()

In [20]:
clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [21]:
y_pred=clf.predict(X_test)
y_pred

array([1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1], dtype=int64)

In [22]:
y_test

205    0
44     1
821    1
458    1
795    0
      ..
111    0
730    1
105    0
479    1
277    0
Name: Survived, Length: 268, dtype: int64

In [23]:
accuracy_score(y_test,y_pred)*100

71.26865671641791

In [24]:
from sklearn.metrics import accuracy_score, confusion_matrix
confusion_matrix(y_pred, y_test)

array([[130,  48],
       [ 29,  61]], dtype=int64)